
/********************************************************
 *                                                      *
 *                                                      *
 * DON'T EDIT THIS FILE, AUTOGENERATED BY GRUNT TASK    *
 *                                                      *
 *                                                      *
 ********************************************************/

var config = {}

config.api = {"port":"9327"};

module.exports = config;

